# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Go.gitlab-ci.yml

image: golang:latest

stages:
  - test
  - build

lint-and-format:
  stage: test
  script:
    - go fmt ./...
    - go vet ./...
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
    - golangci-lint run

test:
  stage: test
  coverage: '/total:\s+\(statements\)\s+\d+.\d+%/'
  script:
    - go test ./... -coverprofile=coverage.txt -covermode count -timeout 30s
    - go tool cover -func coverage.txt
    - go test -race ./... -timeout 1m
  after_script:
    - go get github.com/boumenot/gocover-cobertura
    - go run github.com/boumenot/gocover-cobertura < coverage.txt > coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

compile:
  stage: build
  script:
    - mkdir -p bin
    - go build -o bin ./...
  artifacts:
    paths:
      - bin


